# Generated by Django 3.2 on 2021-05-01 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('role', models.CharField(blank=True, default='Unspecified', max_length=100)),
                ('description', models.TextField(blank=True, max_length=2500, null=True)),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='')),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male'), ('T', 'Transgender'), ('O', 'Others')], max_length=100, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['user', 'role'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill', models.CharField(help_text='Hard skills you possess', max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(help_text='Talk about how exciting your project is and what it entails!', max_length=2500)),
                ('preferred_role', models.CharField(max_length=100)),
                ('development_phase', models.CharField(choices=[('ID', 'Ideation'), ('PL', 'Planning'), ('DES', 'Design'), ('DEV', 'Development'), ('DEP', 'Deployed')], help_text='Choose your current development phase', max_length=200)),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.profile')),
                ('members', models.ManyToManyField(blank=True, help_text='Add your team members to this project', related_name='_core_project_members_+', to='core.Profile')),
                ('preferred_skills', models.ManyToManyField(blank=True, help_text='Choose skills you prefer in your potential teammate', related_name='_core_project_preferred_skills_+', to='core.Skill')),
                ('team_skills', models.ManyToManyField(blank=True, help_text='Choose skills your team has', related_name='_core_project_team_skills_+', to='core.Skill')),
            ],
            options={
                'ordering': ['created_date', 'title', 'creator'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Choose technical skills you have', to='core.Skill'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True, default='I am interested in working on this project!', max_length=1500)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'ordering': ['profile', 'project'],
            },
        ),
    ]
