# Generated by Django 3.2 on 2021-05-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.PositiveSmallIntegerField(default=1, help_text='The number of teammates on your project, including yourself'),
        ),
        migrations.AlterField(
            model_name='project',
            name='preferred_role',
            field=models.CharField(help_text="Preferred applicant's role", max_length=100),
        ),
    ]
