# Generated by Django 3.2 on 2021-05-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210502_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Name of Project, Team or Topics if undecided', max_length=200),
        ),
    ]
