# Generated by Django 3.2 on 2021-05-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='expected_end_date',
            field=models.DateField(blank=True, help_text='mm/dd/yyyy', null=True),
        ),
    ]
